[package]
name = "rustinst"
version = "0.1.0"
authors = ["tytjan <adrianczech-1997@wp.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config =    {path = "./config" }
commander = {path = "./commander" }